/**
  Redux actions constants
**/

// index using cozy-stack mango
export const INDEX_GEOLOCATIONS_BY_DATE = 'INDEX_GEOLOCATIONS_BY_DATE'
export const INDEX_GEOLOCATIONS_BY_DATE_SUCCESS = 'INDEX_GEOLOCATIONS_BY_DATE_SUCCESS'

// fetch geolocations
export const FETCH_GEOLOCATIONS = 'FETCH_GEOLOCATIONS'
export const RECEIVE_GEOLOCATIONS = 'RECEIVE_GEOLOCATIONS'
export const FETCH_GEOLOCATIONS_FAILURE = 'FETCH_GEOLOCATIONS_FAILURE'
