/**
  Redux actions constants
**/

// index using cozy-stack mango
export const INDEX_GEOLOCATIONS_BY_DATE = 'INDEX_GEOLOCATIONS_BY_DATE'
export const INDEX_GEOLOCATIONS_BY_DATE_SUCCESS = 'INDEX_GEOLOCATIONS_BY_DATE_SUCCESS'
export const INDEX_PHONECALLS_BY_DATE= 'INDEX_PHONECALLS_BY_DATE'
export const INDEX_PHONECALLS_BY_DATE_SUCCESS = 'INDEX_PHONECALLS_BY_DATE_SUCCESS'

// fetch geolocations
export const FETCH_GEOLOCATIONS = 'FETCH_GEOLOCATIONS'
export const RECEIVE_GEOLOCATIONS = 'RECEIVE_GEOLOCATIONS'
export const FETCH_GEOLOCATIONS_FAILURE = 'FETCH_GEOLOCATIONS_FAILURE'
export const FETCH_GEO_LAST_DAY = 'FETCH_GEO_LAST_DAY'

// select date
export const SELECT_DATE = 'SELECT_DATE'

// fetch phonecalls
export const RECEIVE_PHONECALLS = 'RECEIVE_PHONECALLS'
export const FETCH_PHONECALLS_FAILURE = 'FETCH_PHONECALLS_FAILURE'

// fet top points
export const RECEIVE_TOP_GEOLOCATIONS = 'RECEIVE_TOP_GEOLOCATIONS'
export const RECEIVE_TOP_PHONECALLS = 'RECEIVE_TOP_PHONECALLS'
